\ test-pieces.fs

REQUIRE ffl/tst.fs
REQUIRE pieces.fs
REQUIRE display.fs

." pieces" CR
."     have a category and an orientation" CR
T{
    1  NTH-SHAPE DUP CATEGORY CROSS-SHAPES ?S ORIENTATION 0 ?S
    63 NTH-SHAPE DUP CATEGORY HOUSE-SHAPES ?S ORIENTATION 7 ?S
    15 NTH-SHAPE DUP CATEGORY BRIDGE-SHAPES ?S ORIENTATION 3 ?S
    14 NTH-SHAPE DUP CATEGORY BRIDGE-SHAPES ?S ORIENTATION 2 ?S
}T
."     have a list of square relative coords" CR
: REORDER 2>R SWAP 2R> SWAP 2SWAP ;
T{
    1 COORDS REORDER 15 ?S 16 ?S 17 ?S 32 ?S
    ' .SHARP IS (.BLOCK)
    1 COORDS 3 10 .SHAPE
    2 COORDS 6 10 .SHAPE
    3 COORDS 12 10 .SHAPE
    4 COORDS 18 10 .SHAPE
    5 COORDS 24 10 .SHAPE
    6 COORDS 30 10 .SHAPE
    7 COORDS 36 10 .SHAPE
    0 20 AT-XY
    ' .COORDS IS (.BLOCK)
    1 COORDS 10 10 .SHAPE CR
    2 COORDS 20 10 .SHAPE CR
    3 COORDS 30 10 .SHAPE CR
    BYE
}T




