\ test-pieces.fs

REQUIRE ffl/tst.fs
REQUIRE pieces.fs

." pieces" CR

."    have shapes and positions that are iterated over" CR 
T{
    -1 -1 SHAPE-INDEX 2!
    NEXT-SHAPE-INDEX SHAPE-INDEX 2@ SWAP PIECE UPPERI ?S 0 ?S
    NEXT-SHAPE-INDEX SHAPE-INDEX 2@ SWAP PIECE UPPERI ?S 1 ?S
    NEXT-SHAPE-INDEX SHAPE-INDEX 2@ SWAP PIECE SNAKE  ?S 0 ?S
    NEXT-SHAPE-INDEX SHAPE-INDEX 2@ SWAP PIECE SNAKE  ?S 1 ?S
    NEXT-SHAPE-INDEX SHAPE-INDEX 2@ SWAP PIECE SNAKE  ?S 2 ?S
    NEXT-SHAPE-INDEX SHAPE-INDEX 2@ SWAP PIECE SNAKE  ?S 3 ?S
    NEXT-SHAPE-INDEX SHAPE-INDEX 2@ SWAP PIECE SNAKE  ?S 4 ?S
    NEXT-SHAPE-INDEX SHAPE-INDEX 2@ SWAP PIECE SNAKE  ?S 5 ?S
    NEXT-SHAPE-INDEX SHAPE-INDEX 2@ SWAP PIECE SNAKE  ?S 6 ?S
    NEXT-SHAPE-INDEX SHAPE-INDEX 2@ SWAP PIECE SNAKE  ?S 7 ?S
    NEXT-SHAPE-INDEX SHAPE-INDEX 2@ SWAP PIECE UPPERL ?S 0 ?S
    11 0 SHAPE-INDEX 2!
    
}T
